### ISSUE TITLE
Rescue contracts with legacy PDUs and Orbital Dock

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#679] opened 2015-10-10 10:27 UTC
I regularly receive rescue contracts where the rescuee is sitting in the MKS or OKS "legacy" PDU, as well as some where they are in the Orbital Dock.

Since this way I basically get a free PDU or even Orbital Dock already in orbit and just need to push it a bit to my station, this is probably not intentional.

Rescue contracts with USI parts should be limited to parts that aren't super useful, and exclude legacy parts completely.

**Comment by BobPalmer** [comment] 2015-10-12 18:32
This is a TAC-LS issue (and a very bad design decision that is one of the reasons I had to break from supporting TAC-LS natively).  Closing as it's up to Taranis to stop assuming anything with a crew wants to have a test contract and breaking other mods.

**Closed by BobPalmer** 2015-10-12 18:32 UTC
Labels: Support Request

**Comment by jd284** [comment] 2015-10-13 16:22
Sorry but I don't think that's it. I've uninstalled TAC-LS (deleted the entire ThunderAerospace folder) to test this, then cleared (rejected) the existing contracts, but I still immediately get new rescue contracts with the MKS_EL_OrbitalDock, MKV.Pod, MKV.AuxCon and MKV.Workshop parts (as seen in the astronaut center after accepting).
I also didn't see anything in the TAC-LS files to support this, it only adds the LifeSupportModule to all parts with CrewCapacity, and the ModuleTestSubject specifically only to the stock crew parts.
It might still be a stock issue of course, or maybe with the IVA settings that USI reuses, but I don't think it's correct to blame TAC-LS.

**Comment by BobPalmer** [comment] 2015-10-13 16:50
Whoops - sorry was thinking the test contracts (which TAC-LS adds and broke everything to hell), vs Rescue Contracts.

**Comment by BobPalmer** [comment] 2015-10-13 16:57
Confirmed this is stock behavior for anything with a seat - no way to get around it for rescue contracts, so leaving this closed.
