### ISSUE TITLE
MKS container weirdness.

### ISSUE THREAD

**Issue by Tabris83** [BobPalmer/MKS#492] opened 2015-06-08 05:44 UTC
this is the 3.75m kontainer. 

![screenshot45](https://cloud.githubusercontent.com/assets/8855255/8028646/2f479942-0df5-11e5-95c7-51709dd9f361.png)

**Comment by Tabris83** [comment] 2015-06-08 08:48
launched another one and the same happened while i was "disposing" of the first one.
it launched properly but after launch and docking (then leaving KSP open while i had dinner) i came back to it like this.
![screenshot46](https://cloud.githubusercontent.com/assets/8855255/8031053/d409bb72-0e0e-11e5-8b13-68514da71e01.png)

**Comment by lstanden** [comment] 2015-07-14 06:39
I just had the same thing happen to me on the Kontainer Tank... I've now got what looks like the "smallest" Kontainer sitting in the middle of a craft which was built around 3.75m tank.

**Comment by lstanden** [comment] 2015-07-14 06:45
My steps (don't know if it's reproducable every time this way) was to inject craft into orbit, then decouple my orbital insertion stage and de-orbit it.  I then switched back to the craft and found the container bugged.

The capacity looks correct, but the size is just all wrong.

**Comment by Kerbas-ad-astra** [comment] 2015-07-15 02:34
I remember reading somewhere that this sudden shrinkage on returning to a vessel can happen when a part that has an other-than-1 "rescaleFactor" (as the size 3 Kontainers do) is used as the first part of a vessel.  I think it was in the context of TweakScale, though it might be a stock bug -- do you have that installed?

**Comment by geoffromer** [comment] 2015-07-15 16:18
FWIW, I've experienced this issue, and I've never had TweakScale installed.

**Comment by BobPalmer** [comment] 2016-01-16 19:21
Closing

**Closed by BobPalmer** 2016-01-16 19:21 UTC
Labels: Investigate

**Comment by qm3ster** [comment] 2016-01-16 19:48
Was this fixed, or should we just not use resized models as root parts?
