### ISSUE TITLE
OKS Farms Do not work in orbit- Happiness zero

### ISSUE THREAD

**Issue by MisterNineThousand** [BobPalmer/MKS#553] opened 2015-07-03 18:12 UTC
My orbital farm got about 4500% production on the ground, but gets 25% production now that it's in orbit. 

Station
-3 Two Star Engineers
- 9 Hab rings and 9 Agri inflateables
- An OKS Kerbitat and an Aeroponics, with 2000 Machinery each
- PDU (Also capped at 25%)
-10000 fertilizer 65000 Mulch, 65000 Organics Space for 65000 Supplies. 

Logs;
Eff = 0
effparts =0 
Workunits=0
Kerbalmodfactor = 0
HappyKerbalModFactor=0
NumWorkspaces =3
AdjNumWorkspaces =27

Looks to be the exact same issue that's come up a few times on the MKS forums best example being Page 1076 by monkeybusiness (He posted screenshots)

Thanks!

**Comment by MisterNineThousand** [comment] 2015-07-09 02:21
Confirmed on Version 31.4

Also impacting PDUs, which is handy since I can watch them during flight

I was able to get it up to 250% output on the surface, and at T+ 20s (1100M altitude) It went back to 25% productivity. I assume it sweeps for happiness every 20 seconds?

**Comment by scolebrook** [comment] 2015-07-11 00:04
I can confirm setting landed to true in quicksave file restores expected efficiency values (but sets orbital speed to 0m/s). MKS is only calculating efficiency for landed vessels and because a station isn't landed, it's giving the minimum of 25%.

**Comment by BobPalmer** [comment] 2015-07-16 23:18
Check this again in 0.31.5

**Closed by BobPalmer** 2015-07-16 23:18 UTC
Labels: Next Release

**Comment by scolebrook** [comment] 2015-07-17 02:59
@BobPalmer Thx. Issue resolved for me.
